[packages]
name  # description
# [coreutils    "Cross-platform rewrite of GNU coreutils"]
# [caliguda   "nicer dd replacement, burning tool"]
bat  # cat clone
mdcat  # cat for markdown
bandwhich  # display current network utilization by process, connection and remote host
bob-nvim
bottom  # graphical process/system monitor for the terminal.
heatseeker  # fuzzy selector, a selecta clone
broot  # explore file hierarchies with a tree-like view
rathole  # expose a service NAT to the Internet (like ngrok)
cargo-update  # update dependencies as recorded in local lock file
diskonaut  # find whale files that eat up disk space
fclones  # finds and removes duplicate files
fd-find  # find entries in your filesystem
gimoji  # copy emoji to clipboard, or add them to commit messages
hexyl  # hex viewer
just  # just a command runner https://github.com/casey/just
gitu  # git client inspired by Magit
ripgrep_all  # ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz, etc.
killport  # kill processes running on specied port
kondo  # Kondo recursively cleans project directories.
miniserve  # serve some files over HTTP right now!
mprocs  # tui for running multiple processes
nu  # nushell language and shell
ouch  # extract/compress files
pastel  # generate, analyze, convert and manipulate colors
pgen  # passphrase generator
pueue  # run tasks in the background
rustscan
sccache  # build caching tool
tealdeer  # TLDR client
trippy  # network diagnostic tool
xh  # http requests
hurl  # run HTTP requests defined in a simple plain text format
