[python]
frida-tools = "dynamic instrumentation toolkit for devs"
magic-wormhole = "get things from one computer to another, safely"
litecli = "CLI for SQLite Databases with auto-completion and syntax highlighting "
ipython = "repl"
img2pdf = "lossless conversion of rater images to pdf"
honcho = "Foreman clone, manage Procfile apps"
ipdb = "better pdb"
chardet = "character encoding detector"
yt-dlp = "audo video downloader"
# memray
python-benedict = "dict subclass with keylist/keypath support, built-in I/O operations (base64, csv, html, ini, json, pickle, plist, query-string, toml, xls, xml, yaml), s3 support and many utilities."

[rust-pkgs]
coreutils = "Cross-platform rewrite of GNU coreutils"
# caliguda = "nicer dd replacement, burning tool"
bat = "cat clone"
# mdcat = "cat for markdown"
bandwhich = "display current network utilization by process, connection and remote host"
starship = "cross-shell prompt"
bob-nvim = "nvim version manager"
bottom = "graphical process/system monitor for the terminal."
heatseeker = "fuzzy selector, a selecta clone"
broot = "explore file hierarchies with a tree-like view"
rathole = "expose a service NAT to the Internet (like ngrok)"
difftastic = ""
diskonaut = "find whale files that eat up disk space"
fclones = "finds and removes duplicate files"
fd-find = "find entries in your filesystem"
gimoji = "copy emoji to clipboard, or add them to commit messages"
# hexyl = "hex viewer"
just = "just a command runner https://github.com/casey/just"
gitu = "git client inspired by Magit"
ripgrep_all = "ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz, etc."
killport = "kill processes running on specied port"
kondo = "Kondo recursively cleans project directories."
miniserve = "serve some files over HTTP right now!"
mprocs = "tui for running multiple processes"
nu = "nushell language and shell"
ouch = "extract/compress files"
pastel = "generate, analyze, convert and manipulate colors"
pgen = "passphrase generator"
rustscan = "network scanner"
tealdeer = "TLDR client"
trippy = "network diagnostic tool"
xh = "http requests"
# hurl = "run HTTP requests defined in a simple plain text format"

[rust-dev-pkgs]
# py-spy = "python sample profiler"
# amp
amber = "replace things in files (sed like tool)"
ast-grep = "Search and Rewrite code at large scale using precise AST pattern"
bacon = "watches your rust project and runs jobs in background"
biodiff = ""
cargo-binutils = ""
cargo-edit = ""
cargo-expand = ""
cargo-info = ""
cargo-mutants = ""
cargo-show-asm = ""
cargo-sweep = ""
cargo-udeps = ""
cargo-update = "update dependencies as recorded in local lock file"
cargo-watch = ""
checkexec = "conditionally execute commands only when files in a dependency list have been updated"
fastmod = ""
fnm = ""
git-absorb = "git commit --fixup, but automatic"
git-delta = ""
huniq = "remove duplicates from input"
hwatch = "watch command"
mdbook = ""
sccache = "build caching tool"
secure_remove = ""
tokei = "count lines of code"
viddy = "modern watch command, time machine and pager"
watchexec-cli = ""

[fedora]
bat = "better cat"
cascadia-mono-nf-fonts = "cascadia with nerdfont"
curl = "cli data transfer"
fd-find = "a better find"
flameshot = "powerful yet simple screenshots"
gh = "github cli"
git = "git"
just = "command runner"
neovim = "nvim"
ocrmypdf = "adds OCR layer to scanned PDF files, allowing them to be searched"
restic = "backup  things"
ripgrep = "a better grep"
rustup = "manage rust toolchains"
sshfs = "mount remote locations via ssh"
syncthing = "continuous file synchronization"
tealdeer = "tldr commands"
thunderbird = "mail reader"
wireguard-tools = "vpn"

[debian]
# https://omakub.org/ opinionated setup
# "Easy scrollable window tiling: https://github.com/paperwm/PaperWM"
bat = "better cat"
build-essential = ""
curl = "cli data transfer"
fail2ban = ""
fd-find = "a better find"
ffmpeg = "format media conversion"
flameshot = "powerful yet simple screenshots"
gh = "github cli"
git = "git"
neovim = "nvim"
printer-driver-splix = "samsung drivers"
restic = "backup things"
rfkill = ""
ripgrep = "a better grep"
rsync = "backup things"
sshfs = "mount remote locations via ssh"
syncthing = "continuous file synchronization"
vlc = "media player"
# printer
printer-driver-all = "many printer drivers"
openprinting-ppds = "printer drivers"
avahi-utils = "publish and discover services, e.g. printers"

[windows]
# https://xournalpp.github.io/installation/windows/
#
# "sysinternals https://learn.microsoft.com/en-us/sysinternals/downloads/"
# winget upgrade --slient --all
#
# random list for windows:
# Ditto Eartrumpet Xmousebuttoncontrol
# sketchup8 dupeguru winmerge handbrake
#
# available packages at https://github.com/microsoft/winget-pkgs/
7zip.7zip = ""
Audacity.Audacity = ""
BurntSushi.ripgrep.MSVC = ""
Casey.Just = ""
DBBrowserForSQLite.DBBrowserForSQLite = ""
Flameshot.Flameshot = "powerful yet simple screenshots"
GIMP.GIMP = ""
Git.Git = ""
GitHub.GitHubDesktop = ""
GitHub.GitLFS = ""
GitHub.cli = ""
GoLang.Go = ""
Graphviz.Graphviz = ""
JesseDuffield.lazygit = ""
Kitware.CMake = ""
Microsoft.AzureCLI = ""
Neovide.Neovide = ""
Ninja-build.Ninja = ""
Nushell.Nushell = ""
OBSProject.OBSStudio = ""
Python.Python.3.12 = ""
Rustlang.Rustup = ""
SumatraPDF.SumatraPDF = ""
Terrastruct.D2 = ""
VideoLAN.VLC = ""
bmatzelle.Gow = ""
charmbracelet.glow = ""
gerardog.gsudo = ""
# junegunn.fzf = ""
mesonbuild.meson = ""
sharkdp.fd = ""
wez.wezterm = ""

[mac-brew]
fd = ""
gh = ""
git = ""
lazygit = ""
neovim = ""
restic = ""
ripgrep = ""
vlc = ""

[mac-brew-cask]
flameshot = ""
gimp = ""
neovim = ""
nushell = ""
obs = ""
vlc = ""
wezterm = ""

