[python]
ocrmypdf = "adds OCR layer to scanned PDF files, allowing them to be searched"
cogapp = "generate content with inlined Python code. https://nedbatchelder.com/code/cog"
hypothesis = "find edge cases in your code"
MechanicalSoup = "automate interaction with websites, (no Javascript, for js see Selenium)"
frida-tools = "dynamic instrumentation toolkit for devs"
magic-wormhole = "get things from one computer to another, safely"
litecli = "CLI for SQLite Databases with auto-completion and syntax highlighting "
ipython = "repl"
img2pdf = "lossless conversion of rater images to pdf"
honcho = "Foreman clone, manage Procfile apps"
ipdb = "better pdb"
chardet = "character encoding detector"
yt-dlp = "audo video downloader"
# memray
python-benedict = "dict subclass with keylist/keypath support, built-in I/O operations (base64, csv, html, ini, json, pickle, plist, query-string, toml, xls, xml, yaml), s3 support and many utilities."

[rust-pkgs]
coreutils = "Cross-platform rewrite of GNU coreutils"
# caliguda = "nicer dd replacement, burning tool"
bat = "cat clone"
# mdcat = "cat for markdown"
bandwhich = "display current network utilization by process, connection and remote host"
starship = "cross-shell prompt"
jimaku = "subtitle downloader, OPEN_SUBTITLES_API_KEY from https://www.opensubtitles.com/en/consumers"
bob-nvim = "nvim version manager"
bottom = "graphical process/system monitor for the terminal."
heatseeker = "fuzzy selector, a selecta clone"
broot = "explore file hierarchies with a tree-like view"
difftastic = ""
# biodiff = ""
diskonaut = "find whale files that eat up disk space"
fclones = "finds and removes duplicate files"
fd-find = "find entries in your filesystem"
gimoji = "copy emoji to clipboard, or add them to commit messages"
# hexyl = "hex viewer"
just = "just a command runner https://github.com/casey/just"
gitu = "git client inspired by Magit"
ripgrep_all = "ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz, etc."
killport = "kill processes running on specied port"
kondo = "Kondo recursively cleans project directories."
miniserve = "serve some files over HTTP right now!"
mprocs = "tui for running multiple processes"
nu = "nushell language and shell"
ouch = "extract/compress files"
# pastel = "generate, analyze, convert and manipulate colors"
pgen = "passphrase generator"
rustscan = "network scanner"
tailspin = "log file highlighter"
tealdeer = "TLDR client"
trippy = "network diagnostic tool"
xh = "http requests"
# hurl = "run HTTP requests defined in a simple plain text format"
hwatch = "watch command"

[rust-dev-pkgs]
# py-spy = "python sample profiler"
# amp
amber = "replace things in files (sed like tool)"
ast-grep = "Search and Rewrite code at large scale using precise AST pattern"
bacon = "watches your rust project and runs jobs in background"
cargo-binutils = ""
cargo-edit = "commands for modifying cargo.toml"
cargo-expand = "expand rust macros"
cargo-info = "query crates.io for crate details"
cargo-mutants = "injects bugs and see if tests catch them"
# cargo-show-asm = "show generated assembly of rust code"
cargo-sweep = "cleans unused build files created by cargo"
cargo-udeps = "find unused dependencies"
cargo-update = "update dependencies as recorded in local lock file"
cargo-watch = "watch over cargo project"
checkexec = "conditionally execute commands only when files in a dependency list have been updated"
fastmod = "replace for programmers"
fnm = "node.js manajer"
git-absorb = "git commit --fixup, but automatic"
git-delta = "syntax-highlighting pager for git"
huniq = "remove duplicates from input"
mdbook = "creates book from markdown files"
rathole = "expose a service NAT to the Internet (like ngrok)"
samply = "cli sampling profiler, check performance, something hangs?"
sccache = "build caching tool"
secure_remove = "securely remove files and dirs"
tokei = "count lines of code"
watchexec-cli = "execute commands in response to modifications"

[fedora]
# ocrmypdf = "adds OCR layer to scanned PDF files, allowing them to be searched"
# tesseract-osd = "orientation detection (needeb by ocrmypdf)"
age = "modern secure encryption tool"
bat = "better cat"
cascadia-mono-nf-fonts = "cascadia with nerdfont"
curl = "cli data transfer"
fd-find = "a better find"
flameshot = "powerful yet simple screenshots"
gh = "github cli"
git = "git"
golang = "go programming language"
gron = "make json greppable"
just = "command runner"
neovim = "nvim"
restic = "backup  things"
ripgrep = "a better grep"
rustup = "manage rust toolchains"
sshfs = "mount remote locations via ssh"
syncthing = "continuous file synchronization"
tealdeer = "tldr commands"
thunderbird = "mail reader"
wireguard-tools = "vpn"

[debian]
# https://omakub.org/ opinionated setup
# "Easy scrollable window tiling: https://github.com/paperwm/PaperWM"
age = "modern secure encryption tool"
bat = "better cat"
build-essential = ""
golang = "go programming language"
curl = "cli data transfer"
fail2ban = ""
fd-find = "a better find"
ffmpeg = "format media conversion"
flameshot = "powerful yet simple screenshots"
gh = "github cli"
git = "git"
gron = "make json greppable"
neovim = "nvim"
printer-driver-splix = "samsung drivers"
restic = "backup things"
rfkill = ""
ripgrep = "a better grep"
rsync = "backup things"
sshfs = "mount remote locations via ssh"
syncthing = "continuous file synchronization"
vlc = "media player"
# printer
printer-driver-all = "many printer drivers"
openprinting-ppds = "printer drivers"
avahi-utils = "publish and discover services, e.g. printers"

[windows]
# https://xournalpp.github.io/installation/windows/
#
# "sysinternals https://learn.microsoft.com/en-us/sysinternals/downloads/"
# winget upgrade --slient --all
#
# random list for windows:
# Ditto Eartrumpet Xmousebuttoncontrol
# sketchup8 dupeguru winmerge handbrake
#
# available packages at:
#    https://github.com/microsoft/winget-pkgs/
"7zip.7zip" = ""
"FiloSottile.age" = "modern secure encryption tool"
"Audacity.Audacity" = ""
"BurntSushi.ripgrep.MSVC" = ""
"Casey.Just" = ""
"DBBrowserForSQLite.DBBrowserForSQLite" = ""
"Flameshot.Flameshot" = "powerful yet simple screenshots"
"GIMP.GIMP" = ""
"Git.Git" = ""
"GitHub.GitHubDesktop" = ""
"GitHub.GitLFS" = ""
"GitHub.cli" = ""
"GoLang.Go" = "go programming language"
"Graphviz.Graphviz" = ""
"JesseDuffield.lazygit" = ""
"KeePassXCTeam.KeePassXC" = ""
"Kitware.CMake" = ""
"Microsoft.AzureCLI" = ""
"Microsoft.PowerToys" = ""
"Microsoft.VisualStudioCode" = ""
"Mozilla.SOPS" = "editor of encrypted files that supports YAML, JSON, ENV, INI and BINARY formats and encrypts with AWS KMS, GCP KMS, Azure Key Vault, age, and PGP"
"Neovide.Neovide" = ""
"Ninja-build.Ninja" = ""
"Nushell.Nushell" = ""
"OBSProject.OBSStudio" = ""
"Python.Python.3.12" = ""
"Rustlang.Rustup" = ""
"SumatraPDF.SumatraPDF" = ""
"Terrastruct.D2" = ""
"TomHudson.gron" = "make json greppable"
"VideoLAN.VLC" = ""
"bmatzelle.Gow" = ""
"charmbracelet.glow" = ""
"gerardog.gsudo" = ""
"mesonbuild.meson" = ""
"sharkdp.fd" = ""
"wez.wezterm" = ""
"x64dbg.x64dbg" = "debugger"
# "junegunn.fzf" = ""

[mac-brew]
fd = ""
gh = ""
git = ""
lazygit = ""
neovim = ""
restic = ""
ripgrep = ""
vlc = ""

[mac-brew-cask]
flameshot = ""
gimp = ""
neovim = ""
nushell = ""
obs = ""
vlc = ""
wezterm = ""

